# Define metrics with their type and formatted name
metric_info = [
    {'metric': 'frac_q3_wi', 'type': 'Asymmetry', 'fmt_name': 'Frac Q3'},
    {'metric': 'frac_q3', 'type': 'Asymmetry', 'fmt_name': 'Frac Q3'},
    {'metric': 'peak_mean_ratio', 'type': 'Peakiness', 'fmt_name': 'Peak-mean ratio'},
    {'metric': 'cv', 'type': 'Peakiness', 'fmt_name': 'Cv'},
    {'metric': 'frac_q1_wi', 'type': 'Asymmetry', 'fmt_name': 'Frac Q1'},
    {'metric': 'frac_q1', 'type': 'Asymmetry', 'fmt_name': 'Frac Q1'},    
    {'metric': 'time_kurtosis', 'type': 'Asymmetry', 'fmt_name': '(T) kurtosis'},
    {'metric': 'Mean Intensity HIZ', 'type': 'Peakiness', 'fmt_name': 'Mean Intensity HIZ'},
    {'metric': '% rain HIZ', 'type': 'Concentration', 'fmt_name': '% rain HIZ'},
    {'metric': 'frac_q2_wi', 'type': 'Asymmetry', 'fmt_name': 'Frac Q2'},
    {'metric': 'frac_q2', 'type': 'Asymmetry', 'fmt_name': 'Frac Q2'},    
    {'metric': 'event_dry_ratio', 'type': 'Intermittency', 'fmt_name': 'Event-dry ratio'},
    {'metric': 'lorenz_asymetry', 'type': 'Concentration', 'fmt_name': 'Lorenz Asymm.'},
    {'metric': 'm5_wi', 'type': 'Asymmetry', 'fmt_name': 'm5'},
    {'metric': 'm5', 'type': 'Asymmetry', 'fmt_name': 'm5'},    
    {'metric': 'D50', 'type': 'Asymmetry', 'fmt_name': '$D_{50}$'},
    {'metric': 'm1', 'type': 'Asymmetry', 'fmt_name': 'm1'},
    {'metric': 'Event Loading', 'type': 'Asymmetry', 'fmt_name': 'Event Loading'},
    {'metric': 'time_to_peak', 'type': 'Asymmetry', 'fmt_name': 'Time to peak'},
    {'metric': 'asymm_d', 'type': 'Asymmetry', 'fmt_name': 'Asymm. dependence'},
    {'metric': 'centre_gravity', 'type': 'Asymmetry', 'fmt_name': 'CoG'},
    {'metric': 'centre_gravity_interpolated', 'type': 'Asymmetry', 'fmt_name': 'CoG (interp.)'},    
    {'metric': 'max_intensity', 'type': 'Peakiness', 'fmt_name': 'Max intensity'},
    {'metric': 'm3_wi', 'type': 'Asymmetry', 'fmt_name': 'm3'},
    {'metric': 'm3', 'type': 'Asymmetry', 'fmt_name': 'm3'},
    {'metric': 'kurtosis', 'type': 'Peakiness', 'fmt_name': '(C) kurtosis'},
    {'metric': 'skewp', 'type': 'Asymmetry', 'fmt_name': '$Skew_{p}$'},
    {'metric': 'I30', 'type': 'Peakiness', 'fmt_name': 'I30'},
    {'metric': 'peak_position_ratio', 'type': 'Asymmetry', 'fmt_name': 'Peak position ratio'},
    {'metric': 'std', 'type': 'Peakiness', 'fmt_name': '(C) Std'},
    {'metric': 'PCI', 'type': 'Concentration', 'fmt_name': 'PCI'},
    {'metric': 'time_skewness', 'type': 'Asymmetry', 'fmt_name': '(T) skewness'},
    {'metric': 'time_std', 'type': 'Concentration', 'fmt_name': '(T) std'},    
    {'metric': 'm1_wi', 'type': 'Asymmetry', 'fmt_name': 'm1'},
    {'metric': 'm1', 'type': 'Asymmetry', 'fmt_name': 'm1'},    
    {'metric': 'mean_intensity', 'type': 'Peakiness', 'fmt_name': 'Mean intensity'},
    {'metric': 'intermittency', 'type': 'Intermittency', 'fmt_name': 'Intermittency'},
    {'metric': 'T75', 'type': 'Asymmetry', 'fmt_name': 'T75'},
    {'metric': 'relative_amp', 'type': 'Peakiness', 'fmt_name': 'Relative amplitude'},
    {'metric': 'NRMSE_P', 'type': 'Concentration', 'fmt_name': '$NMRSE_{p}$'},
    {'metric': 'm2_wi', 'type': 'Peakiness', 'fmt_name': 'm2'},
    {'metric': 'm2', 'type': 'Peakiness', 'fmt_name': 'm2'},
    {'metric': '% time LIZ', 'type': 'Concentration', 'fmt_name': '% time LIZ'},
    {'metric': 'm4_wi', 'type': 'Asymmetry', 'fmt_name': 'm4'},
    {'metric': 'm4', 'type': 'Asymmetry', 'fmt_name': 'm4'},
    {'metric': 'T25', 'type': 'Asymmetry', 'fmt_name': 'T25'},
    {'metric': 'm2', 'type': 'Peakiness', 'fmt_name': 'm2'},
    {'metric': 'skewness', 'type': 'Peakiness', 'fmt_name': '(C) skewness'},
    {'metric': '% time HIZ', 'type': 'Concentration', 'fmt_name': '% time HIZ'},
    {'metric': 'centre_gravity_interpolated', 'type': 'Asymmetry', 'fmt_name': 'CoG (interp.)'},
    {'metric': 'frac_q4_wi', 'type': 'Concentration', 'fmt_name': 'Frac Q4'},
    {'metric': 'frac_q4', 'type': 'Concentration', 'fmt_name': 'Frac Q4'},    
    {'metric': 'gini', 'type': 'Concentration', 'fmt_name': 'Gini'},
    {'metric': 'TCI', 'type': 'Concentration', 'fmt_name': 'TCI'},
    {'metric': '3rd_ARR', 'type': 'Categorical', 'fmt_name': '3rd ($D_{50}$)'},
    {'metric': '3rd_rcg', 'type': 'Categorical', 'fmt_name': '3rd (CoG)'},
    {'metric': '3rd_w_most', 'type': 'Categorical', 'fmt_name': '3rd with most'},
    {'metric': '4th_w_most', 'type': 'Categorical', 'fmt_name': '4th with most'},
    {'metric': '5th_w_most', 'type': 'Categorical', 'fmt_name': '5th with most'},
    {'metric': 'third_ppr', 'type': 'Categorical', 'fmt_name': '3rd (ppr)'},
    {'metric': '3rd_w_peak', 'type': 'Categorical', 'fmt_name': '3rd with peak'},
    {'metric': '4th_w_peak', 'type': 'Categorical', 'fmt_name': '4th with peak'},
    {'metric': '5th_w_peak', 'type': 'Categorical', 'fmt_name': '5th with peak'},
    {'metric': 'min_intensity', 'type': 'Peakiness', 'fmt_name': 'Min Intensity'},
]

# Create the mappings
type_mapping = {d['metric']: d['type'] for d in metric_info}
name_mapping = {d['metric']: d['fmt_name'] for d in metric_info}
