# dict_types = {"I30": '', 
#             'time_to_peak' : '',
#             'peak_position_ratio': '',
#             'std': '',
#             'max_intensity': '',
#             'mean_intensity': '',
#             'min_intensity': '',              
#             'cv': '' ,
#             'skewness': '',
#             'kurtosis': '', 
#             'relative_amp': '', 
#             'peak_mean_ratio': '', 
#             'PCI':'',
#             'TCI':'',
#             'asymm_d': '',
#             'Event Loading':'',
#             'NRMSE_P':"",
#             'skewp' : '', 
#             'gini': '',
#             'lorenz_asymmetry': '', 
#             'intermittency':'Stochastic event generation', 
#             'event_dry_ratio':'', 
#             'ni':"Characterising profiles",
#             'time_skewness': '', 
#             'time_kurtosis': '', 
#             'centre_gravity': '',
#             'centre_gravity_interpolated': '', 
#             'm1' : 'Characterising profiles', 
#             'm2': 'Characterising profiles', 
#             'm3' : 'Characterising profiles', 
#             'm4': 'Characterising profiles', 
#             'm5': 'Characterising profiles', 
#             'm1_wi' : 'Characterising profiles',
#             'm2_wi': 'Characterising profiles', 
#             'm3_wi' : 'Characterising profiles',
#             'm4_wi': 'Characterising profiles', 
#             'm5_wi': 'Characterising profiles', 
#             '% time HIZ':'',
#             '% time LIZ':'',
#             '% rain HIZ':'',
#             'Mean Intensity HIZ': '', 
#             '3rd_w_peak': '', 
#             '4th_w_peak': '',
#             '5th_w_peak': '', 
#             '3rd_maxpct': '',
#             '3rd_com': '',
#             '3rd_ARR': '',
#             'T25': '',
#             'T75': '',              
#             'T50': '',
#             'D50': '', 
#             'BSC_Index': '',
#              "frac_q1":'',
#              "frac_q4":'',
#              "frac_q2":'',
#               "frac_q3":''
#              }

dict_types = {"I30": 'Intensity', 
            'time_to_peak' : 'Timing of Peak',
            'peak_position_ratio': 'Timing of Peak',
             'third_ppr': 'Timing of Peak',
            'std': 'Peakiness',
            'max_intensity': 'Intensity',
            'mean_intensity': 'Intensity',
            'min_intensity': 'Intensity',              
            'cv': 'Peakiness' ,
            'skewness': 'Peakiness',
            'kurtosis': 'Peakiness', 
            'relative_amp': 'Peakiness', 
            'peak_mean_ratio': 'Peakiness', 
              'peak_mean_ratio_scaled': 'Peakiness', 
            'PCI':'Concentration',
            'TCI':'Concentration',
            'asymm_d': 'Asymmetry',
            'Event Loading':'Asymmetry',
             "event_loading_ghanghas":'Asymmetry',
            'NRMSE_P':"Peakiness",
            'skewp' : 'Timing of peak', 
            'gini': 'Concentration',
            'lorenz_asymmetry': 'Asymmetry', 
            'intermittency':'Intermittency', 
            'event_dry_ratio':'Intermittency', 
            'ni':"Peakiness",
            'time_skewness': 'Asymmetry', 
            'time_kurtosis': 'Asymmetry', 
            'centre_gravity': 'Asymmetry',
            'centre_gravity_interpolated': 'Asymmetry', 
            'm1' : 'Timing of Peak', 
            'm2': 'Peakiness/concentration', 
            'm3' : 'Front loading', 
            'm4': 'Front loading', 
            'm5': 'Front loading', 
            'm1_wi' : 'Timing of Peak',
            'm2_wi': 'Peakiness/concentration', 
            'm3_wi' : 'Asymmetry',
            'm4_wi': 'Asymmetry', 
            'm5_wi': 'Front loading', 
            '% time HIZ':'Concentration',
            '% time LIZ':'Concentration',
            '% rain HIZ':'Concentration',
            'Mean Intensity HIZ': 'Intensity', 
            '3rd_w_peak': 'Timing of Peak', 
            '4th_w_peak': 'Timing of Peak',
            '5th_w_peak': 'Timing of Peak', 
              
            '3rd_w_most': 'Asymmetry', 
            '4th_w_most': 'Asymmetry',
            '5th_w_most': 'Asymmetry',               
              
            '3rd_maxpct': 'Asymmetry',
            '3rd_rcg': 'Asymmetry',
            '3rd_ARR': 'Asymmetry',
            'T25': 'Asymmetry',
            'T75': 'Asymmetry',              
            'T50': 'Asymmetry',
            'D50': 'Asymmetry', 
            'BSC_Index': 'Asymmetry',
             "frac_q1":'Asymmetry',
             "frac_q4":'Asymmetry',
             "frac_q2":'?',
            "frac_q3":'?',
             "frac_q1_wi":'Asymmetry',
             "frac_q4_wi":'Asymmetry',
             "frac_q2_wi":'?',
              "frac_q3_wi":'?',              
              'third ppr':'Timing of peak'
             }


names_lookup = {"I30": 'Intensity', 
            'time_to_peak' : 'Time to peak',
            'peak_position_ratio': 'Peak position ratio',
             'third_ppr': 'Third with peak position ratio',
            'std': 'Standard deviation',
            'max_intensity': 'Max intensity',
            'mean_intensity': 'Mean intensity',
            'min_intensity': 'Min intensity',              
            'cv': 'Coefficient Variation' ,
            'skewness': 'Skewness',
            'kurtosis': 'Kurtosis', 
            'relative_amp': 'Relative Amplitude', 
            'peak_mean_ratio': 'Peak:mean ratio', 
            'peak_mean_ratio_scaled': 'Peak:mean ratio (scaled)', 
            'PCI':'PCI',
            'TCI':'TCI',
            'asymm_d': 'Asymmetry of dependence',
            'Event Loading':'Event Loading',
             "event_loading_ghanghas":'Event Loading',
            'NRMSE_P':"NRMSE_P",
            'skewp' : 'SkewP', 
            'gini': 'Gini Index',
            'lorenz_asymmetry': 'Lorenz Asymmetry', 
            'intermittency':'Intermittency', 
            'event_dry_ratio':'Event:dry ratio', 
            'ni':"Rainfall intensity irregularity",
            'time_skewness': 'Time-based skewness', 
            'time_kurtosis': 'Time-based kurtosis', 
            'centre_gravity': 'Centre of gravity',
            'centre_gravity_interpolated': 'Centre of gravity (interp.)', 
            'm1' : 'm1', 
            'm2': 'm2', 
            'm3' : 'm3', 
            'm4': 'm4', 
            'm5': 'm5', 
            'm1_wi' : 'm1 (interp.)',
            'm2_wi': 'm2 (interp.)', 
            'm3_wi' : 'm3 (interp.)',
            'm4_wi': 'm4 (interp.)', 
            'm5_wi': 'm5 (interp.)', 
            '% time HIZ':'% time HIZ',
            '% time LIZ':'% time LIZ',
            '% rain HIZ':'% rain HIZ',
            'Mean Intensity HIZ': 'Mean Intensity HIZ', 
                
            '3rd_w_peak': '3rd with peak', 
            '4th_w_peak': '4th with peak',
            '5th_w_peak': '5th with peak', 
                
            '3rd_w_most': '3rd with most rainfall', 
            '4th_w_most': '4th with most rainfall',
            '5th_w_most': '5th with most rainfall',               
              
            '3rd_maxpct': '3rd with max percent',
            '3rd_rcg': '3rd with centre gravity',
            '3rd_ARR': '3rd with D50',
                
            'T25': 'T25',
            'T75': 'T75',              
            'T50': 'T50',
            'D50': 'D50', 
            'BSC_Index': 'BSC_Index',
             "frac_q1":'% rain in Q1',
             "frac_q2":'% rain in Q2',                
             "frac_q3":'% rain in Q3',
             "frac_q4":'% rain in Q4',

             "frac_q1_wi":'% rain in Q1 (interp.)',
             "frac_q2_wi":'% rain in Q2 (interp.)',
             "frac_q3_wi":'% rain in Q3 (interp.)',
             "frac_q4_wi":'% rain in Q4 (interp.)',              
    
             }