# dict_types = {"I30": '', 
#             'time_to_peak' : '',
#             'peak_position_ratio': '',
#             'std': '',
#             'max_intensity': '',
#             'mean_intensity': '',
#             'min_intensity': '',              
#             'cv': '' ,
#             'skewness': '',
#             'kurtosis': '', 
#             'relative_amp': '', 
#             'peak_mean_ratio': '', 
#             'PCI':'',
#             'TCI':'',
#             'asymm_d': '',
#             'Event Loading':'',
#             'NRMSE_P':"",
#             'skewp' : '', 
#             'gini': '',
#             'lorentz_asymetry': '', 
#             'intermittency':'Stochastic event generation', 
#             'event_dry_ratio':'', 
#             'ni':"Characterising profiles",
#             'time_skewness': '', 
#             'time_kurtosis': '', 
#             'centre_gravity': '',
#             'centre_gravity_interpolated': '', 
#             'm1' : 'Characterising profiles', 
#             'm2': 'Characterising profiles', 
#             'm3' : 'Characterising profiles', 
#             'm4': 'Characterising profiles', 
#             'm5': 'Characterising profiles', 
#             'm1_wi' : 'Characterising profiles',
#             'm2_wi': 'Characterising profiles', 
#             'm3_wi' : 'Characterising profiles',
#             'm4_wi': 'Characterising profiles', 
#             'm5_wi': 'Characterising profiles', 
#             '% time HIZ':'',
#             '% time LIZ':'',
#             '% rain HIZ':'',
#             'Mean Intensity HIZ': '', 
#             '3rd_w_peak': '', 
#             '4th_w_peak': '',
#             '5th_w_peak': '', 
#             '3rd_maxpct': '',
#             '3rd_com': '',
#             '3rd_ARR': '',
#             'T25': '',
#             'T75': '',              
#             'T50': '',
#             'D50': '', 
#             'BSC_Index': '',
#              "frac_q1":'',
#              "frac_q4":'',
#              "frac_q2":'',
#               "frac_q3":''
#              }

dict_types = {"I30": 'Intensity', 
            'time_to_peak' : 'Timing of Peak',
            'peak_position_ratio': 'Timing of Peak',
             'third_ppr': 'Timing of Peak',
            'std': 'Peakiness',
            'max_intensity': 'Intensity',
            'mean_intensity': 'Intensity',
            'min_intensity': 'Intensity',              
            'cv': 'Peakiness' ,
            'skewness': 'Peakiness',
            'kurtosis': 'Peakiness', 
            'relative_amp': 'Peakiness', 
            'peak_mean_ratio': 'Peakiness', 
              'peak_mean_ratio_scaled': 'Peakiness', 
            'PCI':'Concentration',
            'TCI':'Concentration',
            'asymm_d': 'Asymmetry',
            'Event Loading':'Asymmetry',
             "event_loading_ghanghas":'Asymmetry',
            'NRMSE_P':"Peakiness",
            'skewp' : 'Timing of peak', 
            'gini': 'Concentration',
            'lorentz_asymetry': 'Asymmetry', 
            'intermittency':'Intermittency', 
            'event_dry_ratio':'Intermittency', 
            'ni':"Peakiness",
            'time_skewness': 'Asymmetry', 
            'time_kurtosis': 'Asymmetry', 
            'centre_gravity': 'Asymmetry',
            'centre_gravity_interpolated': 'Asymmetry', 
            'm1' : 'Timing of Peak', 
            'm2': 'Peakiness', 
            'm3' : 'Asymmetry', 
            'm4': 'Asymmetry', 
            'm5': 'Asymmetry', 
            'm1_wi' : 'Timing of Peak',
            'm2_wi': 'Peakiness', 
            'm3_wi' : 'Asymmetry',
            'm4_wi': 'Asymmetry', 
            'm5_wi': 'Asymmetry', 
            '% time HIZ':'Concentration',
            '% time LIZ':'Concentration',
            '% rain HIZ':'Concentration',
            'Mean Intensity HIZ': 'Intensity', 
            '3rd_w_peak': 'Asymmetry', 
            '4th_w_peak': 'Asymmetry',
            '5th_w_peak': 'Asymmetry', 
            '3rd_maxpct': 'Asymmetry',
            '3rd_com': 'Asymmetry',
            '3rd_ARR': 'Asymmetry',
            'T25': 'Asymmetry',
            'T75': 'Asymmetry',              
            'T50': 'Asymmetry',
            'D50': 'Asymmetry', 
            'BSC_Index': 'Asymmetry',
             "frac_q1":'Asymmetry',
             "frac_q4":'Asymmetry',
             "frac_q2":'?',
              "frac_q3":'?',
             "frac_q1_wi_":'Asymmetry',
             "frac_q4_wi_":'Asymmetry',
             "frac_q2_wi_":'?',
              "frac_q3_wi_":'?',              
              'third ppr':'Timing of peak'
             }