# Define metrics with their type and formatted name
metric_info = [
    {'metric': 'frac_q1_wi', 'type': 'Mass timing', 'fmt_name': 'Frac Q1', 'type2':'Continuous'},
    #{'metric': 'frac_q1', 'type': 'Mass timing', 'fmt_name': 'Frac Q1'},          

    {'metric': 'm3_wi', 'type': 'Mass timing', 'fmt_name': 'm3'},
    #{'metric': 'm3', 'type': 'Mass timing', 'fmt_name': 'm3'},    
    {'metric': 'm4_wi', 'type': 'Mass timing', 'fmt_name': 'm4'},
    #{'metric': 'm4', 'type': 'Mass timing', 'fmt_name': 'm4'},    
    {'metric': 'm5_wi', 'type': 'Mass timing', 'fmt_name': 'm5'},
    #{'metric': 'm5', 'type': 'Mass timing', 'fmt_name': 'm5'},   

    {'metric': 'time_skewness', 'type': 'Mass timing', 'fmt_name': '(T) skewness'},
    {'metric': 'centre_gravity', 'type': 'Mass timing', 'fmt_name': 'CoG'},
    #{'metric': 'centre_gravity_interpolated', 'type': 'Mass timing', 'fmt_name': 'CoG (interp.)'}, 
    {'metric': 'T25', 'type': 'Mass timing', 'fmt_name': 'T25'},       
    {'metric': 'D50', 'type': 'Mass timing', 'fmt_name': '$D_{50}$'},    
    {'metric': 'T75', 'type': 'Mass timing', 'fmt_name': 'T75'},
    {'metric': '3rd_ARR', 'type': 'Mass timing', 'fmt_name': '3rd ($D_{50}$)'},
    {'metric': '3rd_rcg', 'type': 'Mass timing', 'fmt_name': '3rd (CoG)'},
    {'metric': '3rd_w_most', 'type': 'Mass timing', 'fmt_name': '3rd with most'},
    {'metric': '4th_w_most', 'type': 'Mass timing', 'fmt_name': '4th with most'},
    {'metric': '5th_w_most', 'type': 'Mass timing', 'fmt_name': '5th with most'},
    
    {'metric': 'm1_wi', 'type': 'Peak timing', 'fmt_name': 'm1'},
    #{'metric': 'm1', 'type': 'Mass timing', 'fmt_name': 'm1'},
    {'metric': 'time_to_peak', 'type': 'Peak timing', 'fmt_name': 'Time to peak'},
    {'metric': 'skewp', 'type': 'Peak timing', 'fmt_name': '$Skew_{p}$'},
    {'metric': 'peak_position_ratio', 'type': 'Peak timing', 'fmt_name': 'Peak position ratio'},
    {'metric': 'third_ppr', 'type': 'Peak timing', 'fmt_name': '3rd (ppr)'},
    {'metric': '3rd_w_peak', 'type': 'Peak timing', 'fmt_name': '3rd with peak'},
    {'metric': '4th_w_peak', 'type': 'Peak timing', 'fmt_name': '4th with peak'},
    {'metric': '5th_w_peak', 'type': 'Peak timing', 'fmt_name': '5th with peak'},
    #{'metric': 'min_intensity', 'type': 'Peak timing', 'fmt_name': 'Min Intensity'},

    {'metric': 'I30', 'type': 'Magnitude concentration', 'fmt_name': 'I30'},
    {'metric': 'max_intensity', 'type': 'Magnitude concentration', 'fmt_name': 'Max intensity'},     
    {'metric': 'std', 'type': 'Magnitude concentration', 'fmt_name': '(C) Std'},    
    {'metric': 'kurtosis', 'type': 'Magnitude concentration', 'fmt_name': '(C) kurtosis'},
    {'metric': 'skewness', 'type': 'Magnitude concentration', 'fmt_name': '(C) skewness'},
    {'metric': 'cv', 'type': 'Magnitude concentration', 'fmt_name': 'Cv'}, 
    {'metric': 'peak_mean_ratio', 'type': 'Magnitude concentration', 'fmt_name': 'Peak-mean ratio'},
    {'metric': 'relative_amp', 'type': 'Magnitude concentration', 'fmt_name': 'Relative amplitude'}, 
    {'metric': 'Mean Intensity HIZ', 'type': 'Magnitude concentration', 'fmt_name': 'Mean Intensity HIZ'},
    {'metric': '% rain HIZ', 'type': 'Magnitude concentration', 'fmt_name': '% rain HIZ'},
    {'metric': '% time LIZ', 'type': 'Magnitude concentration', 'fmt_name': '% time LIZ'}, 
    {'metric': '% time HIZ', 'type': 'Magnitude concentration', 'fmt_name': '% time HIZ'},
    {'metric': 'NRMSE_P', 'type': 'Magnitude concentration', 'fmt_name': '$NMRSE_{p}$'},
    {'metric': 'm2_wi', 'type': 'Magnitude concentration', 'fmt_name': 'm2'},
    #{'metric': 'm2', 'type': 'Magnitude concentration', 'fmt_name': 'm2'},    
     {'metric': 'gini', 'type': 'Magnitude concentration', 'fmt_name': 'Gini'},
    #{'metric': 'lorenz_asymetry', 'type': 'Magnitude concentration', 'fmt_name': 'Lorenz Asymm.'}, 
    {'metric': 'lorenz_asymmetry', 'type': 'Magnitude concentration', 'fmt_name': 'Lorenz Asymm.'}, 
    {'metric': 'PCI', 'type': 'Magnitude concentration', 'fmt_name': 'PCI'},
    {'metric': 'event_dry_ratio', 'type': 'Magnitude concentration', 'fmt_name': 'Event-dry ratio'},
    
    {'metric': 'TCI', 'type': 'Temporal concentration', 'fmt_name': 'TCI'},
    {'metric': 'time_kurtosis', 'type': 'Temporal concentration', 'fmt_name': '(T) kurtosis'},
    # {'metric': 'time_std', 'type': 'Temporal concentration', 'fmt_name': '(T) std'},    
   {'metric': 'norm_time_std', 'type': 'Temporal concentration', 'fmt_name': '(T) std'},
    {'metric': 'time_std_norm', 'type': 'Temporal concentration', 'fmt_name': '(T) std'},

    {'metric': 'intermittency', 'type': 'Intermittency', 'fmt_name': 'Intermittency'},
    
    {'metric': 'mean_intensity', 'type': 'Unclassified', 'fmt_name': 'Mean intensity'},
    {'metric': 'frac_q2_wi', 'type': 'Unclassified', 'fmt_name': 'Frac Q2'},
    #{'metric': 'frac_q2', 'type': 'Mass timing', 'fmt_name': 'Frac Q2'},    
    {'metric': 'frac_q3_wi', 'type': 'Unclassified', 'fmt_name': 'Frac Q3'},
    #{'metric': 'frac_q3', 'type': 'Mass timing', 'fmt_name': 'Frac Q3'},
    {'metric': 'frac_q4_wi', 'type': 'Unclassified', 'fmt_name': 'Frac Q4'},
    #{'metric': 'frac_q4', 'type': 'Mass timing', 'fmt_name': 'Frac Q4'},    
     {'metric': 'Event Loading', 'type': 'Unclassified', 'fmt_name': 'Event Loading'},
     {'metric': 'asymm_d', 'type': 'Unclassified', 'fmt_name': 'Asymm. dependence'}]

# Create the mappings
type_mapping = {d['metric']: d['type'] for d in metric_info}
name_mapping = {d['metric']: d['fmt_name'] for d in metric_info}